### ISSUE TITLE
HW feedback

### ISSUE THREAD

**Issue by rfaroul** [eric-h0/pokemonTrivia#1]
Way to separate the js code into different files. It makes it more readable and easier to navigate.

End the game. Don't keep looping through questions. Or give the player the option to end the game.

I would also like to see a countdown of the number of questions remaining.

Another feature that I would add/change/update is the red top bar that says "Good luck!". I would update that every few questions to display different messages like "You're doing really well" (if the player has more correct than incorrect guesses) or "You suck" (if they aren't very good). 

You should also try changing the background every few questions. That'd be a good mini-hw assignment to give yourself. It would make the UI even more incredible than it already is. 

Great job! I love your code.

**Comment by theWallsOfEricHo** [comment]
Thanks, Rachelle! I'll add those to my code.
